// File generated by FlutterFire CLI.
// Adapted manually from firebase.json & google-services.json
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeGV2jkC_ZdloKbX-PgAaj7jguzP4AXMo',
    appId: '1:987278104822:android:8f3682c2f4970daed134d7',
    messagingSenderId: '987278104822',
    projectId: 'ptirecycle',
    storageBucket: 'ptirecycle.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeGV2jkC_ZdloKbX-PgAaj7jguzP4AXMo',
    appId: '1:987278104822:web:77e374db7fb5d744d134d7',
    messagingSenderId: '987278104822',
    projectId: 'ptirecycle',
    storageBucket: 'ptirecycle.firebasestorage.app',
    authDomain: 'ptirecycle.firebaseapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeGV2jkC_ZdloKbX-PgAaj7jguzP4AXMo',
    appId: '1:987278104822:web:cca97db6a523a8c9d134d7',
    messagingSenderId: '987278104822',
    projectId: 'ptirecycle',
    storageBucket: 'ptirecycle.firebasestorage.app',
    authDomain: 'ptirecycle.firebaseapp.com',
  );
}
